# filebeat.inputs:
#   - type: container
#     stream: stdout
#     paths:
#       - "/var/lib/docker/containers/*/*.log"
#     json.keys_under_root: true
#     json.add_error_key: true
#     json.overwrite_keys: true
#     json.expand_keys: true

filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true
      templates:
        - condition:
            contains:
              docker.container.name: "connect-go-boilerplate"
          config:
            - type: container
              paths:
                - "/var/lib/docker/containers/${data.docker.container.id}/*.log"
              processors:
                - add_tags:
                    tags: [json]
                    target: "parser_type"
                - decode_json_fields:
                    fields:
                      - message
                    target: ""
                    overwrite_keys: true
                    add_error_key: true
                    expand_keys: true

processors:
  - add_docker_metadata: ~
  - add_host_metadata: ~

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  indices:
    # - index: "elastic-%{+yyyy.MM.dd}"
    #   when.or:
    #     - equals:
    #         container.name: filebeat
    #     - equals:
    #         container.name: elasticsearch
    #     - equals:
    #         container.name: kibana
    - index: "connect-go-%{+yyyy.MM.dd}"
      when.or:
        - contains:
            container.name: connect-go-boilerplate
