global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: envoy
    metrics_path: /stats/prometheus
    static_configs:
      - targets: ["envoy-proxy:9901"]
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]
